#ifndef _CHASSIS_H
#define _CHASSIS_H

#define PROVIDES_INTRUSION_SENSOR	0x01
#define PROVIDES_FRONT_PANEL_LOCKOUT	0x02
#define PROVIDES_DIAGNOSTIC_INTERRUPT	0x04
#define PROVIDES_POWER_INTERLOCK	0x08

#endif
